name: fwfh_url_launcher
version: 0.6.0
description: WidgetFactory extension to launch A tag via url_launcher plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/core
  url_launcher: ^6.0.3

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
