name: flutter_widget_from_html
version: 0.6.0
description: Flutter package for widget tree building from html that supports hyperlink, image, nested list, etc.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #https://pub.dev/packages/flutter_widget_from_html
  flutter_widget_from_html_core:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/core
  fwfh_cached_network_image:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/fwfh_cached_network_image
  fwfh_chewie:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/fwfh_chewie
  fwfh_svg:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/fwfh_svg
  fwfh_url_launcher:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/fwfh_url_launcher
  fwfh_webview:
    git:
      url: git://github.com/svoza10/flutter_widget_from_html.git
      ref: master
      path: packages/fwfh_webview
  html: ^0.15.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_cached_network_image:
    path: ../fwfh_cached_network_image
  fwfh_chewie:
    path: ../fwfh_chewie
  fwfh_svg:
    path: ../fwfh_svg
  fwfh_url_launcher:
    path: ../fwfh_url_launcher
  fwfh_webview:
    path: ../fwfh_webview

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: any
  network_image_mock: any
  pedantic: any

flutter:
  assets:
    - test/images/
